### ISSUE TITLE
希望增加列出有趣的、高能的时间点的功能，能够用于视频剪辑

### ISSUE THREAD

**Issue by Yuiffy** [JimmyLv/BiliGPT#1]
你搞的这个东西啊，excited！很有意思。
我觉得可以修改一下问法，让ai给出有趣的、高能的时间点，和当时的台词，列出若干个。这样很方便剪辑视频的人对着直播录像进行高能时刻剪辑。

**Comment by Adam-Teng** [comment]
感觉 gpt3模型没能力搞这些

**Comment by Yuiffy** [comment]
> 

我在测试，感觉差不多了
![Uploading 0EEFBAA4-C40A-410B-8D1F-9F864142D014.jpeg…]()

**Comment by Yuiffy** [comment]
![F5AE2A57-B775-457F-BDD1-F53DF49FB7DA](https://user-images.githubusercontent.com/8912753/222399439-40eb9410-cc22-4047-b57d-7c189b89ea83.jpeg)
图片没带上

**Comment by JimmyLv** [comment]
哈哈哈，完全可以的，因为 可以根据弹幕找出高能片段🤣

示例弹幕：https://comment.bilibili.com/986432051.xml

有人提个PR吗？

**Comment by Yuiffy** [comment]
可以的话需要增加切换不同模式的功能，来对chatgpt提出不同的prompt。另外目前好像没在文本里带上时间点，它的时间点都是乱给的。

给出我这边目前测试到的语句：

_上面给了你语音识别出来的字幕，希望作为精彩集锦剪辑师，帮助我找到精彩片段。请先用一句简短的话总结视频梗概。然后找出5个最有趣的或高潮的时间点，针对每个时间点，介绍内容，如果这时的字幕有趣，可以附上字幕。注意不要超过5个时间点，不要重复，用无序列表方式返回。注意之前给的字幕是语音识别的，可能有误，你可以自己修正一下。_

```
[【📝 总结：BV1f84y177T4】](https://www.bilibili.com/video/BV1f84y177T4/)

梗概：三人打完Apex一转参加在线编程比赛codeforces的直播录像。

- 00:17：三人在游戏中寻找队友，却只有三人对战，感叹没有队友的大劣势。
- 03:22：三人在游戏中奋勇杀敌，夺取胜利，但是打得不太好，其中一人直呼“我好菜呀”。
- 09:48：三人在游戏中遭到攻击，其中一人躺在屋里天，被子弹打中，却还活着，感叹“他好像有点卡卡卡活了”。
- 16:12：三人开始在线编程比赛，其中一人发现自己的代码有问题，直呼“我发现我不会了”。
- 20:58：三人讨论着如何hack，其中一人提到“hack是不是你得锁了才能hack啊”，引发笑声。

 via #BiliGPT b.jimmylv.cn
```

**Comment by JimmyLv** [comment]
哈哈哈 你这个prompt确实不错！ 我试试把跳转加上 😁

**Comment by JimmyLv** [comment]
已经加上了！😁

**Comment by JimmyLv** [comment]
![Google Chrome-localhost3000-001701-20230307](https://user-images.githubusercontent.com/4997466/223319198-0fa388b0-04d2-45c8-b533-f90cd4af6b0d.png)
