### ISSUE TITLE
Vercel 部署失败

### ISSUE THREAD

**Issue by zouxingyuks** [JimmyLv/BiliGPT#11]
![image](https://user-images.githubusercontent.com/102451468/223140288-60169a11-18fe-4dd3-8bc8-d071184ac76b.png)

**Comment by JimmyLv** [comment]
你是自己部署的哇？

**Comment by zouxingyuks** [comment]
是的，且已经尝试过更换环境为other

**Comment by JimmyLv** [comment]
确实很奇怪，我写的这个配置nextjs是兼容的

**Comment by JimmyLv** [comment]
你可以再找找文档，去掉那个配置或改成最新的

**Comment by goxofy** [comment]
我也失败了

**Comment by JimmyLv** [comment]
修了修， https://github.com/JimmyLv/BiliGPT/issues/13#issuecomment-1457487167
