### ISSUE TITLE
vercel 部署报错

### ISSUE THREAD

**Issue by goxofy** [JimmyLv/BiliGPT#13]
![image](https://user-images.githubusercontent.com/1695416/223315142-64af9497-57b1-4d79-b6c5-b1d1cd8e569c.png)

**Comment by JimmyLv** [comment]
是因为没有配置 .env 啦

**Comment by goxofy** [comment]
.env是需要独立配置吗？在vercel的环境变量里配置了openai api不行么

**Comment by goxofy** [comment]
@JimmyLv 还是有报错，请帮忙看看

![image](https://user-images.githubusercontent.com/1695416/223333598-e4e31ae1-29fc-460f-9325-9ffe68da0b16.png)

**Comment by JimmyLv** [comment]
我加了太多依赖了，你可能需要自己改改代码。

这个是Sentry监控的配置项。

**Comment by goxofy** [comment]
@JimmyLv 大佬好，请问log输出的这个是什么意思，大概十几秒一条

AnalyticsBrowser loading... {"writeKey":"","cdnURL":"https://cdn.segment.com"}

这个writekey是segement的http api吗？

**Comment by zouxingyuks** [comment]
建议修改一下.env  的说明，告诉用户从 [.example.env](https://github.com/zouxingyuks/bilichat/blob/main/.example.env) 中进行数据修改

**Comment by goxofy** [comment]
@zouxingyuks 我目前就是.example.env 拷贝了一份.env配置的，只是不知道为什么我配置了segement的http api的writekey，他依然十几秒一次

**Comment by JimmyLv** [comment]
可能后边儿我把它去掉吧，我也受到了干扰

**Comment by goxofy** [comment]
@JimmyLv 感谢

**Comment by xingfanxia** [comment]
+1, 可以更新下新的依赖为optional或者加下配置说明吗

**Comment by justinzpc** [comment]
> @JimmyLv 还是有报错，请帮忙看看
> 
> ![image](https://user-images.githubusercontent.com/1695416/223333598-e4e31ae1-29fc-460f-9325-9ffe68da0b16.png)
老哥你解决了吗，我也是卡在这了

**Comment by 0x1FFFFF** [comment]
> @JimmyLv 还是有报错，请帮忙看看
> 
> ![image](https://user-images.githubusercontent.com/1695416/223333598-e4e31ae1-29fc-460f-9325-9ffe68da0b16.png) 老哥你解决了吗，我也是卡在这了

sentry还是强依赖…不是optional

**Comment by JimmyLv** [comment]
哈哈哈 那你们自己去掉一下嘛

**Comment by JimmyLv** [comment]
感谢支持！ 可以呀~ @justinzpc
