### ISSUE TITLE
b站好像有防止脚本获取字幕地址的功能

### ISSUE THREAD

**Issue by Yuiffy** [JimmyLv/BiliGPT#3]
登录账号后在网页上直接访问https://api.bilibili.com/x/web-interface/view?bvid=BV1BY4y117y3 ，能获取到字幕地址；
但是直接用node访问这个api获取，字幕list就是空的。
<img width="200" alt="image" src="https://user-images.githubusercontent.com/8912753/222706423-70ee775b-91c0-4e58-9a38-53063b8bdb05.png">

**Comment by orangelckc** [comment]
获取字幕是有前提的
1. UP主后台开启了字幕
2. 获取ai字幕文件地址需要带着cookie的，UP自己传的字幕不需要
我测试下来是这样的
